version: 2.1
orbs:
  node: circleci/node@1.1.6
  cypress: cypress-io/cypress@1
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn test
      - cypress/run
workflows:
    build-and-test:
      jobs:
        - build-and-test